# Show changes in probability between the last two SFDC reports

prefix dc: <http://purl.org/dc/terms/>

select ?name ?pred ?p1 ?p2 where {
  graph ?g1 {
    ?g1 dc:title "sfdc 2014-12-03" .
      ?s sfdc:opportunity-name ?name ;
    ?pred ?p1 . 
  }
  graph ?g2 {
    ?g2 dc:title "sfdc 2014-12-08" .
      ?s sfdc:opportunity-name ?name ;
    ?pred ?p2 . 
  }
  filter (?p1 != ?p2)
}
order by ?name

# The End
