# Test SPARQL queries

select ?close (sum(?wtd) as ?wtdTotal)
  where {
    {
      # Select the latest graph
      select ?g 
        where { ?g a sfdc:Snapshot . } 
      order by desc(?g) limit 1
    }
    {
      graph ?g {
        ?id a sfdc:Opportunity ;
          sfdc:opportunity-name ?name ;
          sfdc:ps-amount ?deal ;
          sfdc:close-month ?close ;
          sfdc:probability ?prob .

        bind (?deal*?prob/100 as ?wtd)
        filter (?deal > 0) .
      }
    }
  }
group by ?close

