# Test SPARQL queries

prefix dc: <http://purl.org/dc/terms/>

# Select the latest SFDC graph
select ?g1 ?g2
where {
  {
    select ?g1
      where { graph ?g1 { ?g1 a sfdc:Snapshot . } }
    order by desc(?g1) limit 1
  }
  {
    select ?g2
      where { graph ?g2 { ?g2 a sfdc:Snapshot . } }
    order by desc(?g2) offset 1 limit 1
  }
}
