# Show the weighted pipe by close month
prefix dct:   <http://purl.org/dc/terms/>

select ?close (sum(?wtd) as ?wtdTotal) where {
    graph ?g {
      ?g dct:title "sfdc 2014-12-08" .
      ?id sfdc:opportunity-name ?name ;
          sfdc:ps-amount ?deal ;
          sfdc:close-month ?close ;
          sfdc:probability-percent ?prob .
       bind (?deal*?prob/100 as ?wtd)
       filter (?deal > 0) .
    }
}
group by ?close

# The End
